project:
  type: website
  output-dir: docs 
website:
  title: "Preetish Parikh"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



